CREATE DATABASE IF NOT EXISTS fitcheck2;
USE fitcheck2;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  phone VARCHAR(20),
  profile_picture VARCHAR(255)
);
